---

- include_vars: vars/defaults.yml

#########################################################################################
## Install nginx webserver on CentOS machine 
## Refer the below URL to add more parameters to the below ansible role
## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
#########################################################################################

##Install epel release as it is dependent package for nginx
- name: Install epel packages
  yum:
    name: epel-release
    state: absent
  register : install_epel
- debug:
    var: install_epel

##INstall nginx package by using yum module
- name: Install nginx packages 
  yum:
    name: nginx
    state: absent
  register : install_nginx
- debug:
    var: install_nginx

## Ensure nginx is running by using service module
- name: ensure nginx is running
  service:
    name: nginx 
    state: started
  register : start_nginx
- debug:
    var: start_nginx

## Open the port 80 since nginx running on port 80
- name: Open port 80 for nginx access
  firewalld:
    service: nginx
    permanent: true
    state: enabled
  register : enable_port_nginx
- debug:
    var: enable_port_nginx

## Restart the OS firewall by using firewalld module
- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted
  register : restart_firewalld_nginx
- debug:
    var: restart_firewalld_nginx
