---

- include_vars: vars/defaults.yml

#########################################################################################
## Install Apache webserver on CentOS machine 
## Refer the below URL to add more parameters to the below ansible role
## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
#########################################################################################
- name: Install epel packages
  yum:
    name: epel-release
    state: absent
  register : install_epel
- debug:
    var: install_epel

- name: Install nginx packages 
  yum:
    name: nginx
    state: absent
  register : install_nginx
- debug:
    var: install_nginx

- name: ensure nginx is running
  service:
    name: nginx 
    state: started
  register : start_nginx
- debug:
    var: start_nginx

- name: Open port 80 for nginx access
  firewalld:
    service: nginx
    permanent: true
    state: enabled
  register : enable_port_nginx
- debug:
    var: enable_port_nginx

- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted
  register : restart_firewalld_nginx
- debug:
    var: restart_firewalld_nginx
