---

- include_vars: vars/defaults.yml

#########################################################################################
## Install Apache webserver on CentOS machine 
## Refer the below URL to add more parameters to the below ansible role
## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
#########################################################################################

## Install apacje package by using ansible module yum 
- name: Install apache packages 
  yum:
    name: httpd
    state: absent
  register : install_httpd
- debug:
    var: install_httpd


## Ensure the apache service is up and running by using ansible service module 
- name: ensure httpd is running
  service:
    name: httpd 
    state: started
  register : start_httpd
- debug:
    var: start_httpd




## Enable the port 80 by using ansible firewalld module since apache running on port 80
- name: Open port 80 for http access
  firewalld:
    service: httpd
    permanent: true
    state: enabled
  register : enable_port_httpd
- debug:
    var: enable_port_httpd


## Restart OS firewall using  ansible firewalld module
- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted
  register : restart_firewalld_httpd
- debug:
    var: restart_firewalld_httpd
