---

- include_vars: vars/defaults.yml

#########################################################################################
## Install nginx webserver on CentOS machine
## Refer the below URL to add more parameters to the below ansible role
## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
#########################################################################################

##- name: Install epel packages
##  yum:
##    name: epel-release
##    state: latest
##  register : install_epel
##- debug:
##    var: install_epel

##Download Zabbix rpm by using get url module
- name: Download zabbix Community Repo
  get_url:
    url: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
    dest: /tmp
  register : download_zabbix_rpm
- debug:
    var: download_zabbix_rpm

##Install the Zabbix repo by using rpm module
##- name: Install Zabbix Community Repo
##  command: "/usr/bin/rpm -ivh /tmp/zabbix-release-4.0-2.el7.noarch.rpm"
##  register : install_zabbix_rpm
##- debug:
##    var: install_zabbix_rpm


- name: Install zabbix packages
  yum:
    name: zabbix-agent
    state: latest
  register : install_zabbix
- debug:
    var: install_zabbix

##Start the mysql server by using service module
- name: Start MySQL Server and enable it
  service:
    name: zabbix-agent
    state: started
    enabled: yes
  register : start_zabbix
- debug:
    var: start_zabbix
